-- USER SQL
CREATE USER BDPRUEBA IDENTIFIED BY ROOT 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER BDPRUEBA QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO BDPRUEBA;
GRANT "RESOURCE" TO BDPRUEBA;
ALTER USER BDPRUEBA DEFAULT ROLE "CONNECT","RESOURCE";
