/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import clase.Cl_Coneccion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author LSP
 */
public class RegistroMedicamentos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMedicamentos
     */
    public RegistroMedicamentos() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/fox.png"));
        setIconImage(icon);
        setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);

        btnAtras.setBackground(Color.decode("#eb0c0f"));
        btnGrabar2.setBackground(Color.decode("#eb0c0f"));
        //cboCantidad.setBackground(Color.decode("#ffffff"));
        this.getContentPane().setBackground(Color.decode("#ffffff"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnGrabar2 = new javax.swing.JButton();
        txtCodigoAM = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtTipoMedicamento = new javax.swing.JTextField();
        txtComponente = new javax.swing.JTextField();
        txtGramaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtContenido = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();

        jLabel8.setText("Gramaje");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Registrar Nuevo Medicamentos");

        btnAtras.setBackground(new java.awt.Color(255, 0, 0));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGrabar2.setBackground(new java.awt.Color(255, 0, 0));
        btnGrabar2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGrabar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabar2.setText("Agregar");
        btnGrabar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabar2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Art o medicamento");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Tipo Medicamento");

        jLabel5.setText("Componentes");

        jLabel6.setText("Fabricante");

        jLabel7.setText("Contenido");

        jLabel9.setText("Cantidad");

        jLabel10.setText("Gramaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoAM)
                            .addComponent(txtDescripcion)
                            .addComponent(txtFabricante)
                            .addComponent(txtTipoMedicamento)
                            .addComponent(txtComponente)
                            .addComponent(txtContenido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGramaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrabar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGramaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    //ARREGLAR METODO PARA REINICIAR CAMPOS AL AGREGAR

    private void btnGrabar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabar2ActionPerformed
        //iniciamos conexion BD
        Cl_Coneccion conectarse = new Cl_Coneccion();
        Connection entrar = conectarse.getConnection();
        Statement st;

        //VALIDAMOS EL FORMULARIO PARA AGREGAR UN MEDICAMENTO.
        if (txtCodigoAM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Codigo sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtCodigoAM.requestFocus();
            return;
        }
        if (txtDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Descripcion sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtDescripcion.requestFocus();
            return;
        }
        if (txtFabricante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fabricante sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtFabricante.requestFocus();
            return;
        }

        if (txtTipoMedicamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tipo Medicamento sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtTipoMedicamento.requestFocus();
            return;
        }
        if (txtComponente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Componente Activo sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtComponente.requestFocus();
            return;
        }
        if (txtContenido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Contenido sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtContenido.requestFocus();
            return;
        }
        //Arreglar CBO Cantidad
        if (txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cantidad sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtCantidad.requestFocus();
            return;
        }
        if (txtGramaje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Gramaje sin datos", "Error!!!", JOptionPane.INFORMATION_MESSAGE);
            txtGramaje.requestFocus();
            return;
        }

        //CREAMOS VARIABLES PARA LA INSERCION EN LA BD
        String xCodigoAM = txtCodigoAM.getText();
        String xDescripcion = txtDescripcion.getText();
        String xFabricante = txtFabricante.getText();
        String xTipoMedicamento = txtTipoMedicamento.getText();
        String xComponentes = txtComponente.getText();
        String xContenido = txtContenido.getText();
        String xCantidad = txtCantidad.getText();
        String xGramaje = txtGramaje.getText();
        //llamamos a la query de insercion desde este boton
        // String registrar  = "INSERT INTO ARTICULO_Y_MEDICA VALUES (?,?,?,?,?,?,?,?)";
        String registrar = "INSERT INTO ARTICULO_Y_MEDICA VALUES ('" + xCodigoAM + "','" + xDescripcion + "','" + xFabricante + "','" + xTipoMedicamento + "','" + xComponentes + "','" + xContenido + "','" + xCantidad + "','" + xGramaje + "')";
        try {

            st = entrar.createStatement();
            st.executeQuery(registrar);
            JOptionPane.showMessageDialog(rootPane, "Registrado Con exito");

            //reiniciarmos los campos a blanco
            txtCodigoAM.setText("");
            txtComponente.setText("");
            txtGramaje.setText("");
            txtDescripcion.setText("");
            txtFabricante.setText("");
            txtTipoMedicamento.setText("");
            //cboCantidad.setValue(0);
            txtGramaje.setText("");

        } catch (Exception e) {
            //si existe un error nos tira este error
            JOptionPane.showMessageDialog(null, "Error en :" + e);
        }


    }//GEN-LAST:event_btnGrabar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMedicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGrabar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoAM;
    private javax.swing.JTextField txtComponente;
    private javax.swing.JTextField txtContenido;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtGramaje;
    private javax.swing.JTextField txtTipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
